=== ecn3/myCOP4856/Exercises/JavaXMLExercise1/JavaXMLExercise1/src/movie.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT movie (director|imdbRef|year|metascore|rottenTomatoes|keywords)*>
<!ATTLIST movie id CDATA #IMPLIED >

<!ELEMENT director (#PCDATA)>
<!ELEMENT imdbRef (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT metascore (#PCDATA)>
<!ELEMENT rottenTomatoes (#PCDATA)>
<!ELEMENT keywords (keyword*)>
<!ELEMENT keyword (#PCDATA)>

=== ecn3/myCOP4856/Exercises/JavaXMLExercise1/JavaXMLExercise1/src/movie2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE movie  SYSTEM "movie.dtd">
<?xml-stylesheet type="text/css" href="movie.css"?>
<!-- This XML document describes a movieÂ  -->
<movie>
   <director>Zack Snyder</director>
   <imdbRef>tt0770828</imdbRef>
   <year>2013</year>
   <metascore>55</metascore>
   <rottenTomatoes>82</rottenTomatoes>
   <keywords>
      <keyword>manofsteel</keyword>
   </keywords>
</movie>
