=== ecn3/myCOP4856/Projects/Project1/src/playList.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/playList.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE playList SYSTEM "playList.dtd">

    <playList>
    ...
    </playList>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT playList (movie)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT movie (director|title|runTime|productionCompany|imdbRef|year|metascore|rottenTomatoes|keywords)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT director (name|birthdate)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT birthdate (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT title (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT runTime (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT productionCompany (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT imdbRef (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT year (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT metascore (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT rottenTomatoes (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT keywords (keyword)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT keyword (#PCDATA)>

=== ecn3/myCOP4856/Projects/Project1/src/playList.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE playList  SYSTEM "playList.dtd">
<?xml-stylesheet type="text/css" href="playList.css"?>
<!-- This XML document describes a playlist of movies -->
<playList>
    
<movie>
   <director>
	<name>Chris Columbus</name>
	<birthdate>9/10/1958</birthdate>
   </director>
   <title>Harry Potter and the Chamber of Secrets</title>
   <runTime>161</runTime>
   <productionCompany>Warner Bros.</productionCompany>
   <imdbRef>tt0295297</imdbRef>
   <year>2002</year>
   <metascore>63</metascore>
   <rottenTomatoes>82</rottenTomatoes>
   <keywords>
      <keyword>harrypotter</keyword>
      <keyword>jkrowlings</keyword>
   </keywords>
</movie>

<movie>
   <director>
	<name>Zack Snyder</name>
	<birthdate>03/01/1966</birthdate>
   </director>
   <title>Man of Steel </title>
   <runTime>143</runTime>
   <productionCompany>Warner Bros.</productionCompany>
   <imdbRef>tt0770828</imdbRef>
   <year>2013</year>
   <metascore>55</metascore>
   <rottenTomatoes>82</rottenTomatoes>
   <keywords>
         <keyword>manofsteel</keyword>
   </keywords>
</movie>

<movie>
   <director>
	<name>Matt Reeves</name>
	<birthdate>04/27/1966</birthdate>
   </director>
   <title>Untitled Batman Reboot</title>
   <runTime></runTime>
   <productionCompany>Warner Bros.</productionCompany>
   <imdbRef>tt1877830</imdbRef>
   <year>2021</year>
   <metascore>n/a</metascore>
   <rottenTomatoes>n/a</rottenTomatoes>
</movie>

</playList>

=== ecn3/myCOP4856/Projects/Project2/src/playList.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE playList  SYSTEM "playList.dtd">
<?xml-stylesheet 
    type="text/xsl" 
    version="2.0"
    href="playList.xsl"?>
<!-- This XML document describes a playlist of movies -->
<playList>
    <movie movieID="m1">
        <director>
            <name>Chris Columbus</name>
            <birthdate>9/10/1958</birthdate>
        </director>
        <title>Harry Potter and the Chamber of Secrets</title>
        <runTime>161</runTime>
        <productionCompany>Warner Bros.</productionCompany>
        <imdbRef>tt0295297</imdbRef>
        <year>2002</year>
        <metascore>63</metascore>
        <rottenTomatoes>82</rottenTomatoes>
        <keywords>
            <keyword keywordID="m1k1">harrypotter</keyword>
            <keyword keywordID="m1k2">jkrowlings</keyword>
        </keywords>
    </movie>

    <movie movieID="m2">
        <director>
            <name>Zack Snyder</name>
            <birthdate>03/01/1966</birthdate>
        </director>
        <title>Man of Steel </title>
        <runTime>143</runTime>
        <productionCompany>Warner Bros.</productionCompany>
        <imdbRef>tt0770828</imdbRef>
        <year>2013</year>
        <metascore>55</metascore>
        <rottenTomatoes>82</rottenTomatoes>
        <keywords>
            <keyword keywordID="m2k1">manofsteel</keyword>
        </keywords>
    </movie>

    <movie movieID="m3">
        <director>
            <name>Matt Reeves</name>
            <birthdate>04/27/1966</birthdate>
        </director>
        <title>Untitled Batman Reboot</title>
        <runTime></runTime>
        <productionCompany>Warner Bros.</productionCompany>
        <imdbRef>tt1877830</imdbRef>
        <year>2021</year>
        <metascore>n/a</metascore>
        <rottenTomatoes>n/a</rottenTomatoes>
    </movie>

</playList>

=== ecn3/myCOP4856/Projects/Project2/src/playList_MissingElement.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE playList  SYSTEM "playList.dtd">
<?xml-stylesheet type="text/css" href="playList.css"?>
<!-- This XML document describes a playlist of movies -->
<playList>
    
    <movie movieID="m1">
        <director>
            <name>Chris Columbus</name>
        </director>
        <title>Harry Potter and the Chamber of Secrets</title>
        <runTime>161</runTime>
        <productionCompany>Warner Bros.</productionCompany>
        <imdbRef>tt0295297</imdbRef>
        <year>2002</year>
        <metascore>63</metascore>
        <rottenTomatoes>82</rottenTomatoes>
    </movie>
</playList>
